API_KEY = "mAJDS6M6RyVJlMiiDyrhS4qY53ZxM4AnFW7ogesTexWXQkfcnT05ByQ28q6tSJ6O"
API_SECRET = "RLKmAOXAsnrhUhMmSEoJhOcSO86OhrrLJYzFKnNMaAAhOch7DgAA9WUSFFCPFKNW"

MODE = "demo"

RISK_PER_TRADE = 0.02
MAX_POSITIONS = 5